(decl (gensym (fn -> symbol)))
(decl (print (fn 'a -> nil)))
(decl (println (fn 'a -> nil)))
(decl (dbg (fn 'a -> 'a)))
(decl (argv (fn -> nil)))
(decl (read-file (fn string -> nil)))
(decl (is-digit? (fn string -> bool)))
(decl (sqrt (fn float -> float)))
(decl (float->int (fn float -> int)))
(decl (int->float (fn int -> float)))
