[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
vm = { path = "../vm" }
identity-hasher = { path = "../identity-hasher" }
gc = { path = "../gc" }
unwrap-enum = { workspace = true }
twox-hash = { workspace = true }
thiserror = "1.0.61"