[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
reader = { path = "../reader" }
vm = { path = "../vm" }
gc = { path = "../gc" }
unwrap-enum = { workspace = true }
micro-nom = { workspace = true }
error = { path = "../error" }
itertools = { workspace = true }