[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
value = { path = "../value" }
vm = { path = "../vm" }
xxhash = { path = "../xxhash" }
identity-hasher = { path = "../identity-hasher" }
unwrap-enum = { workspace = true }
thiserror = "1.0.61"