[workspace]
members = [ "crates/gc","lib/native"]

[workspace.dependencies]
unwrap-enum = { path = "../unwrap-enum" }
twox-hash = "=1.6.3"

[package]
name = "lisp"
version = "0.0.1"
edition = "2021"

[dependencies]
value = { path = "crates/value" }
reader = { path = "crates/reader" }
compiler = { path = "crates/compiler" }
vm = { path = "crates/vm" }
identity-hasher = { path = "crates/identity-hasher" }
native-functions = { path = "lib/native" }
