[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
unwrap-enum = { workspace = true }
thiserror = { workspace = true }
error = { path = "../error" }
identity-hasher = { path = "../identity-hasher" }