[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
identity-hasher = { path = "../identity-hasher" }
gc = { path = "../gc" }
twox-hash = { workspace = true }
unwrap-enum = { workspace = true }
thiserror = "1.0.61"